SELECT
    i.INGREDIENT_TYPE as INGREDIENT_TYPE,
    SUM(f.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF f, ICECREAM_INFO i
WHERE f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY SUM(f.TOTAL_ORDER) ASC