-- 7월의 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량이 큰 순서 상위 3개 맛 조회
SELECT f.FLAVOR 
FROM FIRST_HALF f
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM FROM JULY GROUP BY FLAVOR) j ON f.FLAVOR = j.FLAVOR
ORDER BY JULY_SUM + f.TOTAL_ORDER DESC
LIMIT 3;
